config/routes.rb
Rails.application.routes.draw do
  resources :movies
  get 'users/sign_in', to: "users#sign_in"
  devise_for :users, controllers: { 
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  root "users#dashboard"

  resources :users, only: [:index, :show]
  resources :friendships, only: [:create, :destroy]

end

app/models/concerns/filtrable.rb
module Filtrable
  extend ActiveSupport::Concern
  module ClassMethods
    def filter(filters)
      if !filters.blank?
        results = self.where(nil)
        filters.each do |name, args|
          next unless self.respond_to?(name,args) 
          results = args ? results.public_send(name, args) : results.public_send(name) 
        end
        results
      end
    end
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :inviter, class_name: "User"
  belongs_to :invited, class_name: "User"
  
  validates :invited_id, uniqueness: {scope: :inviter_id, message: "This friendship already exists"}
  validates :inviter_id, presence: true
  validates :invited_id, presence: true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_reader :current_user
  
  has_many :invited_me, class_name: "Friendship", foreign_key: "invited_id"
  has_many :i_invited, class_name: "Friendship", foreign_key: "inviter_id"
  has_many :friends_i_invited, through: :i_invited, source: :invited
  has_many :friends_invited_me, through: :invited_me, source: :inviter
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  include Filtrable
  
  scope :get_user, ->(id) { where id: id }
         
  def my_friends
    self.friends_i_invited + self.friends_invited_me
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: [:show, :index]
  before_action :configure_permitted_parameters, if: :devise_controller?
  layout :set_layout
  after_filter :set_csrf_cookie_for_ng
  
  protected
  
  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end
  
  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  
  def set_layout
    return false if params[:disable_layout].present?
    nil
  end
  
  def authenticate_user!(opts={}) 
    if user_signed_in?
      super
    else
      self.status = :unauthorized
      render json: Hash.new
    end
  end
  
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    Friendship.create({inviter_id: current_user.id, invited_id: params[:friend_id]})
    respond_to do |format|
      format.json { render json: {
        alert: {
          type: "success",
          msg: "Your friend has been added"
        }
        } }
    end
  end
  
  def destroy
    invited_id = params[:id]
    current_user.friends_i_invited.delete(invited_id)
    render json: {
      alert: {
        type: "success",
        msg: "Friendship has been removed"
      }
      }
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :link, :watched)
    end
end

app/controllers/user/custom_failure.rb
class User::CustomFailure < Devise::FailureApp
  def respond
    if request.format == :json or request.content_type == 'application/json' # == :json does not works here
      json_failure
    else
      super
    end
  end

  def json_failure
    self.content_type = 'application/json'
    self.response_body = {"success"=> false, "errors" => http_auth_body}.to_json
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  skip_before_filter :authenticate_user!, :only => :new
  before_filter :configure_permitted_parameter
  
  def create
    respond_to do |format|
      format.json do
        @user = User.new(user_params)
        if @user.save
          render json: { success: { data: @user } }
        else
          render json: { error: @user.errors.full_messages }
        end
      end
    end
  end
  
  protected
  
  def user_params
    params.require(:user).permit([:username, :password, :password_confirmation, :email])
  end
  
  def configure_permitted_parameter
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  prepend_before_action :require_no_authentication, only: [:new, :create]
  prepend_before_action :allow_params_authentication!, only: :create
  prepend_before_action :verify_signed_out_user, only: :destroy
  prepend_before_action only: [:create, :destroy] { request.env["devise.skip_timeout"] = true }
  before_action :authenticate_user!, except: [:new, :create]
  clear_respond_to
  respond_to :json
  skip_before_filter :verify_authenticity_token, only: [:destroy]
  
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:dashboard, :sign_in]
  def dashboard
  end
  
  def index
    respond_to do |format|
      format.html {}
      format.json do
        users = ::Filters::UsersFilter.new(self).run_filters
        render json: users 
      end 
    end 
  end
  
  def show
    respond_to do |format|
      format.html {}
      format.json do  
        users = ::Filters::UsersFilter.new(self).run_filters
        render json: @users 
      end
    end 
  end
  
  def sign_in
    #empty method only because of devise...
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/show.html.haml
%ul{ng: {if: "friends"}, class: "user-list"}
  %li{ng: {repeat: "(k,user) in friends", if: "user"}}
    {{user.username}}
    %a{href: "", ng: {click: "destroy_friendship(user)"}, class: "remove-from-user"} Remove from friends
.empty{ng: {if: "friends.length == 0"}}
  There are no friends

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Movies"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"
  %alerts
  %body{ ng: { app:"app" , controller: "ApplicationController"} }
    %top_nav
    %login{ng: {if: "current_user | isEmpty"}}
    .container
      .row
        .col-lg-12
          %ng-view
      %footer
        %p &copy; Company 2016

app/views/layouts/navigation/_top_menu.html.haml
.navbar.navbar-default.navbar-static-top
  .container
    %a{href: "#/", class: "navbar-brand"} Home
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-right.col-md-6{ng: {if: "current_user | isNotEmpty"}}
        %li.dropdown.col-md-4.pull-right
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "", :role => "button"}
            %i.fa.fa-user &nbsp;
            {{current_user.username}}
            %span.caret
          %ul.dropdown-menu
            %li
              %a{href: "#/users/{{current_user.id}}"} View my account
            %li
              %a{href: "#/users/"} Add friend
            %li
              %a{href: "/users/sign_out", data: {method:"delete"}} Logout

app/views/layouts/navigation/_top_menu0.html.haml
.navbar.navbar-default.navbar-static-top
  .container
    =link_to "Home", root_path, class: "navbar-brand"
    .navbar-collapse.collapse.navbar-responsive-collapse
      -if current_user      
        %ul.nav.navbar-right.col-md-6
          %li.dropdown.col-md-4.pull-right
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              %i.fa.fa-user &nbsp;
              =current_user.username
              %span.caret
            %ul.dropdown-menu
              %li=link_to "Edit my account", edit_registration_path(current_user)
              %li
                %a{href: "#/users"} Add user
              %li= link_to "Friends", users_path
              %li= link_to 'logout', destroy_user_session_path, method: :delete

app/views/movies/_form.html.haml
= form_for @movie do |f|
  - if @movie.errors.any?
    #error_explanation
      %h2= "#{pluralize(@movie.errors.count, "error")} prohibited this movie from being saved:"
      %ul
        - @movie.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :link
    = f.text_field :link
  .field
    = f.label :watched
    = f.check_box :watched
  .actions
    = f.submit 'Save'

app/views/movies/edit.html.haml
%h1 Editing movie

= render 'form'

= link_to 'Show', @movie
\|
= link_to 'Back', movies_path

app/views/movies/index.html.haml
%h1 Listing movies

%table
  %thead
    %tr
      %th Title
      %th Link
      %th Watched
      %th
      %th
      %th

  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.link
        %td= movie.watched
        %td= link_to 'Show', movie
        %td= link_to 'Edit', edit_movie_path(movie)
        %td= link_to 'Destroy', movie, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Movie', new_movie_path

app/views/movies/new.html.haml
%h1 New movie

= render 'form'

= link_to 'Back', movies_path

app/views/movies/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @movie.title
%p
  %b Link:
  = @movie.link
%p
  %b Watched:
  = @movie.watched

= link_to 'Edit', edit_movie_path(@movie)
\|
= link_to 'Back', movies_path

app/views/users/_sign_in_form.html.haml
%h3 Login to Your Account
%form{name: "loginForm", ng:{submit: "login()"}}
  %input{type: "email", required: true , name: "email", ng: {model: "$parent.data.user.email"}, class: "form-control", :placeholder => "Email"}
  %div{ng: {show: "loginForm.email.$dirty && loginForm.email.$error.required"}, class:"invalid-message"} Email field is required
  %div{ng: {show: "loginForm.email.$dirty && loginForm.email.$error.email"}, class:"invalid-message"} Email field should be a valid email addresss
  %input{type: "password", required: true, name: "password", ng: {model: "$parent.data.user.password"}, class: "form-control", :placeholder => "Pasword", autocomplete: "new-password"}
  %div{ng:{show:"loginForm.password.$dirty && loginForm.password.$error.required"}, class:"invalid-message"} Password field is required
  %input.login.loginmodal-submit{:name => "login", :type => "submit", :value => "Login", ng: {disabled: "loginForm.$invalid"} }/
.login-help
  %a{href: "",ng:{click: "goTo('register')"}}Sign up

app/views/users/_sign_up_form.html.haml
%h3 Register New Account
%form{ng:{submit: "register()"}, name: "registrationForm"}
  %input{type: "email", name: "email", ng: {model: "$parent.data.user.email"}, class: "form-control", :placeholder => "Email", required: true}
  %div{class: "invalid-message", ng: {show: "registrationForm.email.$error.required && registrationForm.email.$dirty"}} Email field is required
  %div{class: "invalid-message", ng: {show: "registrationForm.email.$error.email && registrationForm.email.$dirty"}} Email field is invalid
  %input{type: "text", name: "username", ng: {model: "$parent.data.user.username"}, class: "form-control", :placeholder => "Username", required: true}
  %div{class: "invalid-message", ng: {show: "registrationForm.username.$error.required && registrationForm.username.$dirty"}} Username field is required
  %input{type: "password", name: "password", ng: {model: "$parent.data.user.password", minlength: "6"}, class: "form-control", :placeholder => "Pasword", required: true}
  %div{class: "invalid-message", ng: {show: "registrationForm.password.$error.minlength && registrationForm.password.$dirty"}} Password field is too short
  %div{class: "invalid-message", ng: {show: "registrationForm.password.$error.required && registrationForm.password.$dirty"}} Password field is required
  %input{type: "password", name: "password_confirmation", ng: {model: "$parent.data.user.password_confirmation",minlength: "6"}, class: "form-control", :placeholder => "Confirm password", required: true}  
  %div{class: "invalid-message", ng: {show: "registrationForm.password_confirmation.$error.required && registrationForm.password_confirmation.$dirty"}} Password Confirmation field is required
  %div{class: "invalid-message", ng: {show: "registrationForm.password_confirmation.$error.minlength && registrationForm.password.$dirty"}} Password Confirmation field is too short
  %input.login.loginmodal-submit{:name => "login", :type => "submit", :value => "Sign up", ng: {disabled: "registrationForm.$invalid"}}/
.login-help
  %a{href: "",ng:{click: "goTo('login')"}}Sign in

app/views/users/dashboard.html.haml
.row{ ng: { controller: "DashboardController as usersctrl" } }
  hello

app/views/users/index.html.haml
.row{ ng: { controller: "UsersController as usersctrl" } }
  %table.table.table-striped
    %thead.thead-inverse
      %tr
        %th Username
        %th Email
        %th Actions
    %tbody{ ng: { if: "users" }, class: "user-list" }
      %tr{ ng: {repeat: "user in users", if: "user.id != current_user.id && !user.added"} }
        %td {{user.username}}
        %td {{user.email}}
        %td 
          %a{ href: "",  ng:{  click: "usersctrl.add_to_friends(user)" } } Add to friend

app/views/users/show.html.haml
This is my account page
.row.show-grid
  .col-md-5.friends.box
    FRIENDS
    %friends
  .col-md-6.col-md-offset-1.movies.box
    MOVIES

app/views/users/sign_in.html.haml
#login-modal.modal.fade.in{"aria-hidden" => "false", "aria-labelledby" => "myModalLabel", :role => "dialog", :style => "display: block;", :tabindex => "-1"}
  .modal-backdrop.fade.in
  #modal-login.modal-dialog
    .loginmodal-container
      %h1 Credential needed
      %div{ng: {if: "form_error | isNotEmpty", repeat: "(key, value) in form_error"}, class:"invalid-message center"} {{value}}
      %br/
      .login-form-content{ng:{if: "mode=='login'"}}
        =render partial: "sign_in_form"
      .register-form-content{ng:{if: "mode=='register'"}}
        =render partial: "sign_up_form"
        